---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drift-detector
  namespace: drift-detector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: drift-detector
rules:
- apiGroups: ["argoproj.io"]
  resources: ["applications"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: drift-detector
subjects:
- kind: ServiceAccount
  name: drift-detector
  namespace: drift-detector
roleRef:
  kind: ClusterRole
  name: drift-detector
  apiGroup: rbac.authorization.k8s.io
