---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: drift-detector
  namespace: drift-detector
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      serviceAccountName: drift-detector
      containers:
      - name: detector
        image: harbor.kube.chalkan3.com.br/library/drift-detector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NTFY_URL
          value: "https://ntfy.sh"
        - name: NTFY_TOPIC
          value: "k8s-drift-detector"
        - name: CLUSTER_NAME
          value: "kube.chalkan3.com.br"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: 300m
            memory: 512Mi
          requests:
            cpu: 150m
            memory: 256Mi
