---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-check
  namespace: health-check
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: health-check
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-check
subjects:
- kind: ServiceAccount
  name: health-check
  namespace: health-check
roleRef:
  kind: ClusterRole
  name: health-check
  apiGroup: rbac.authorization.k8s.io
