apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-watcher
  namespace: cert-automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-watcher
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-watcher
subjects:
- kind: ServiceAccount
  name: ingress-watcher
  namespace: cert-automation
