apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cert-manager
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - name: cert-manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: NODE_IPS
          valueFrom:
            configMapKeyRef:
              name: mkcert-config
              key: node-ips
        - name: BASE_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: mkcert-config
              key: base-domain
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: ssh-key
          mountPath: /secrets/ssh
          readOnly: true
        - name: mkcert-ca
          mountPath: /certs
          readOnly: true
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
          defaultMode: 0600
      - name: mkcert-ca
        secret:
          secretName: mkcert-ca
