apiVersion: v1
kind: ConfigMap
metadata:
  name: config-domain
  namespace: knative-serving
data:
  # Configuração de domínio padrão
  # Altere para seu domínio customizado se necessário
  svc.cluster.local: ""
