apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: helmfile-rabbitmq
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - list:
        elements:
          - name: rabbitmq
            path: .

  template:
    metadata:
      name: rabbitmq
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: https://git.keite-guica.chalkan3.com.br/chalkan3/helmfile-rabbitmq.git
        targetRevision: HEAD
        path: .
        plugin:
          name: helmfile

      destination:
        server: https://kubernetes.default.svc
        namespace: rabbitmq

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
