apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: cluster-monitor
  namespace: {{ .Release.Namespace }}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "{{ .Values.service.minScale }}"
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      containers:
      - name: monitor
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NTFY_URL
          valueFrom:
            configMapKeyRef:
              name: monitor-config
              key: ntfy-url
        - name: NTFY_TOPIC
          valueFrom:
            configMapKeyRef:
              name: monitor-config
              key: ntfy-topic
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: monitor-config
              key: cluster-name
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
