---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-advisor
  namespace: scaler-advisor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scaler-advisor
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scaler-advisor
subjects:
- kind: ServiceAccount
  name: scaler-advisor
  namespace: scaler-advisor
roleRef:
  kind: ClusterRole
  name: scaler-advisor
  apiGroup: rbac.authorization.k8s.io
