apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-check
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://git.keite-guica.chalkan3.com.br/chalkan3/helmfile-rabbitmq.git
    targetRevision: main
    path: charts/health-check

  destination:
    server: https://kubernetes.default.svc
    namespace: health-check

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
