apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-config
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://git.keite-guica.chalkan3.com.br/chalkan3/helmfile-rabbitmq.git
    targetRevision: HEAD
    path: knative/config

  destination:
    server: https://kubernetes.default.svc
    namespace: knative-serving

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
