---
apiVersion: v1
kind: Service
metadata:
  name: custom-metrics-exporter
  namespace: custom-metrics-exporter
  labels:
    app: custom-metrics-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: custom-metrics-exporter
